索引与切片

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,100,10)
print(a)
print(a[0])
print(a[:]) #获取全部数据
print(a[5]) #注意左闭右开
print(a[a>10])
print(a[(a>10) & (a<50)])
print(a[(a>10) | (a<50)]) #或是|且是&

[ 6 46 86 29 32 38 74 70 60 39]
6
[ 6 46 86 29 32 38 74 70 60 39]
38
[46 86 29 32 38 74 70 60 39]
[46 29 32 38 39]
[ 6 46 86 29 32 38 74 70 60 39]


In [3]:
a = np.random.randint(1,100,(5,5))
print(a)
print(a[3,1])
print(a[:])


[[ 4 84 82 96  4]
 [14 84 24 34 34]
 [66 46 89 14 34]
 [74 82  7  5 22]
 [65 96 71 59 70]]
82
[[ 4 84 82 96  4]
 [14 84 24 34 34]
 [66 46 89 14 34]
 [74 82  7  5 22]
 [65 96 71 59 70]]


In [9]:
a = np.random.randint(1,100,(5,5))
print(a)
print(a[0,:]) #取出第一行元素
print(a[:,0])
print(a[1,1:4])  # 1：4是切片，遵循左闭右开原则
print(a[:,1][a[:,1]>50])#第二列中大于50的元素
print(a[2,:][a[2,:]>50])
print(a[:]>50)


[[44 41 45 52 56]
 [64 55 10  2  6]
 [10 50 38 75 42]
 [ 2 26 52 23 66]
 [91 95 52 70 20]]
[44 41 45 52 56]
[44 64 10  2 91]
[55 10  2]
[55 95]
[75]
[[False False False  True  True]
 [ True  True False False False]
 [False False False  True False]
 [False False  True False  True]
 [ True  True  True  True False]]


In [10]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a)
print(b)
c = a + b
print(c) #np库可以直接矩阵运算

d = [1,2,3]
e = [4,5,6]
for i in range(len(d)):
    e[i] = d[i] + e[i]
print(e) #向量加法必须写循环

[1 2 3]
[3 4 5]
[4 6 8]
[5, 7, 9]


In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,4,5],[4,5,6],[4,5,5]])
print(a)
print(b)
print(a * b) #矩阵每个元素的乘机
print(a @ b) #矩阵乘积的运算

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 4 5]
 [4 5 6]
 [4 5 5]]
[[ 3  8 15]
 [16 25 36]
 [28 40 45]]
[[ 23  29  32]
 [ 56  71  80]
 [ 89 113 128]]
