In [2]:
import numpy as np

In [7]:
a = np.random.randint(0,100,12)
print(a)
b = np.reshape(a,(3,4))
print(b)

[83  7 52 74 69 32 29 50 96 89 25 79]
[[83  7 52 74]
 [69 32 29 50]
 [96 89 25 79]]


In [31]:
print('每一列的平均值为:',np.mean(b,axis=0))
for i in range(b.shape[1]):
    print(f"第 {i + 1} 列的平均值为：{np.mean(b[:, i]):.2f}")

每一列的平均值为: [82.66666667 42.66666667 35.33333333 67.66666667]
第 1 列的平均值为：82.67
第 2 列的平均值为：42.67
第 3 列的平均值为：35.33
第 4 列的平均值为：67.67


In [38]:
print('每一行的平均值为:',np.mean(b,axis=1))
for i in range(b.shape[0]):
    print(f'第{i + 1}行的平均值为:{np.mean(b[i,:]):.2f}')

每一行的平均值为: [54.   45.   72.25]
第1行的平均值为:54.00
第2行的平均值为:45.00
第3行的平均值为:72.25


In [44]:
a = np.random.randint(0,20,(5,5))
print(a)
print(a[a>10])
print(np.where(a>10,0,a))


[[15 16  5  2 17]
 [ 6 14  0  6  4]
 [13  6 16  7 16]
 [ 7 10 19  0 11]
 [ 4 12  8  3  9]]
[15 16 17 14 13 16 16 19 11 12]
[[ 0  0  5  2  0]
 [ 6  0  0  6  4]
 [ 0  6  0  7  0]
 [ 7 10  0  0  0]
 [ 4  0  8  3  9]]


In [51]:
money = np.array([120,135,110,125,135,140])
print(money)
print('最高的月份是:',np.argmax(money)+1)
print('最低的月份是:',np.argmin(money)+1)

[120 135 110 125 135 140]
最高的月份是: 6
最低的月份是: 3


In [55]:
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
c = np.concatenate([a,b]) #矩阵拼接
print(c)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [62]:
a = np.array([1,3,2,1,3,3,5,2,1])
unique_values,counts=np.unique(a, return_counts=True)
print('唯一值分别是:',unique_values)
print('重复次数分别是:',counts)
for value,count in zip(unique_values,counts):
    print(f'{value}出现了{count}次')

唯一值分别是: [1 2 3 5]
重复次数分别是: [3 2 3 1]
1出现了3次
2出现了2次
3出现了3次
5出现了1次
