In [1]:
import numpy as np

In [2]:
print(np.sqrt(4))
a = np.array([1,4,9])
print(np.sqrt(a))
print(np.exp(1))
print(np.log(2.718))

2.0
[1. 2. 3.]
2.718281828459045
0.999896315728952


In [25]:
#计算三角函数
print(np.sin(np.pi/2))
print(np.cos(np.pi))



1.0
-1.0


In [6]:
#绝对值、次幂、五舍六入
a = np.array([[-1,-3,-6],[2,-8,-3]])
print(np.abs(a))
print(np.power(a,3))
b = np.array([3.4,4.5,6.7])
print(np.round(b))  #五舍六入
print(np.ceil(b))  #向上和向下取整
print(np.floor(b))

[[1 3 6]
 [2 8 3]]
[[  -1  -27 -216]
 [   8 -512  -27]]
[3. 4. 7.]
[4. 5. 7.]
[3. 4. 6.]


In [3]:
a = np.array([1,2,4,5])
print(np.sum(a))
b = np.random.randint(1,100,5)
print(b)
print(np.average(b))
print(np.median(b))
print(np.percentile(a,25))  # 有25%的元素比1.75小

12
[67 40 93 66 87]
70.6
67.0
1.75


In [4]:
print(np.var(b))
print(np.std([1,2,3]))

348.24
0.816496580927726


In [17]:
a = np.random.randint(1,100,8)
print(a)
print(np.max(a),np.argmax(a))
print(np.min(a),np.argmin(a))

[58 54 37 23 66 81 55 58]
81 5
23 3
