# 一、ndarray
## ndarray的特性
### 1. 多维性

In [1]:
import numpy as np

In [35]:
a = np.array([1,2,3])
print(a)
print('数组的形状:',a.shape)
print('数组的维度:',a.ndim)
print('数组的个数:',a.size)
print('数据类型:',a.dtype)

[1 2 3]
数组的形状: (3,)
数组的维度: 1
数组的个数: 3
数据类型: int64


In [41]:
a = np.array([ [1,2,3],[2,3,4] ])
print(a)
print('数组的形状:',a.shape)
print('数组的维度:',a.ndim)
print('数组的个数:',a.size)

[[1 2 3]
 [2 3 4]]
数组的形状: (2, 3)
数组的维度: 2
数组的个数: 6


In [3]:
list = [2,3],[3,4]
a = np.array(list,dtype=int)
print(a)
print('数组形状:',a.shape)
print('数组维度:',a.ndim)

[[2 3]
 [3 4]]
数组形状: (2, 2)
数组维度: 2


In [11]:
b = np.copy(a)
print(b)
b[1,0] = 6
print(b)

[[2 3]
 [3 4]]
[[2 3]
 [6 4]]


In [19]:
c = np.zeros(((3,2)),dtype=int)
print(c)
d = np.zeros((5,1),dtype = int)
print(d)

[[0 0]
 [0 0]
 [0 0]]
[[0]
 [0]
 [0]
 [0]
 [0]]


In [64]:
a = np.full((3,4),5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [66]:
a = np.arange(1,10,2)  #左闭右开，开始，结束，步长，不包含结束
print(a)
b = np.linspace(1,10,5)  # linespace参数：开始，结束，步长会自动算出间隔
print(b)

[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
#等比数列
a = np.logspace(0,8,3,base=4,dtype=int)
print(a)

b = np.logspace(0,8,3,dtype=int)
print(b)

[    1   256 65536]
[        1     10000 100000000]


In [9]:
a = np.eye(3)
b = np.eye(3,dtype = int)
print(a)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
a = np.diag([3,4,'b',3])
print(a)

[['3' '' '' '']
 ['' '4' '' '']
 ['' '' 'b' '']
 ['' '' '' '3']]


In [48]:
# 随机生成浮点数矩阵
a = np.random.rand(2,5)  # 生成0-1区间内的2x5矩阵
print(a)
b = np.random.uniform(2,7,(3,4)) #生成2-7之间的3x4矩阵
print(b)

[[0.02572918 0.85520215 0.33871752 0.74710917 0.46064347]
 [0.38625977 0.50254591 0.24505488 0.57029615 0.75478205]]
[[5.99933541 3.25550481 5.56378824 5.56115042]
 [4.09248721 3.7332267  3.6782439  5.52038664]
 [4.15745165 4.86979835 2.08985936 6.02733957]]


In [49]:
a = np.random.randint(3,5,(3,8))
print(a)

[[4 3 3 4 4 3 3 4]
 [4 3 3 4 3 3 3 3]
 [4 3 4 3 3 4 3 4]]


In [55]:
a = np.array([1,2,0],dtype=bool)
print(a)
b = np.array([-128,127],dtype=np.int8)
print(b)


[ True  True False]
[-128  127]
