In [2]:
import numpy as np

In [8]:
a = np.random.randint(1, 100,10
print(a)
print(np.greater(a,10))  #是否大于 小于 等于
print(np.less(a,10))
print(np.equal(a,10))

[69 51 18 96 70 47 41 86 23 22]
[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
[False False False False False False False False False False]


In [15]:
print(np.any([0,0,0,0]))
print(np.any([0,0,0,1])) #检查是否有一部分元素为真
print(np.all([0,0,0,0,0]))
print(np.all([1,1,1,1])) #检查是否全部元素为真


False
True
False
True


In [17]:
print(a)
print(np.where(a>10,a,0)) #从a中找大于10的元素，如果不满足条件则为0  条件 符合条件的 不符合条件的
print(np.where(a>50,1,0))

[69 51 18 96 70 47 41 86 23 22]
[69 51 18 96 70 47 41 86 23 22]
[1 1 0 1 1 0 0 1 0 0]


In [30]:
print(a)
print(np.where(a<60,'不及格',np.where(a<80,'良好','优秀')))
print(np.select([a<60,(a>=60) & (a<=80),a>=80],['不及格','良好','优秀'],default = '未知'))

[49 12 11 74 40 92  5 13 92 52]
['不及格' '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格']
['不及格' '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格']


In [37]:
b = np.random.randint(1,100,10)
print(b)
print(np.sort(b),np.argsort(b),sep = '\n')
print(np.unique(b)) # 去重，会自动排序

[64 10  6 75 58 46 14 77 91 86]
[ 6 10 14 46 58 64 75 77 86 91]
[2 1 6 5 4 0 3 7 9 8]
[ 6 10 14 46 58 64 75 77 86 91]


In [42]:
print(a)
print(b)
print(np.concatenate((a,b)))
print(np.empty_like(a))

[49 12 11 74 40 92  5 13 92 52]
[64 10  6 75 58 46 14 77 91 86]
[49 12 11 74 40 92  5 13 92 52 64 10  6 75 58 46 14 77 91 86]
[ 6 10 14 46 58 64 75 77 86 91]
