In [11]:
import numpy as np

In [12]:
a = np.array([28,30,29,31,32,30,29])
print(a)
print('平均气温是:',np.round(np.mean(a))) #五舍六入
print('平均气温是:%.3f'%np.mean(a))   # 保留三位小数
print('最高温度是:',np.max(a))
print('最低温度是:',np.min(a))
print('气温超过30的天数:',len(a[a>30]))
print('气温超过30的天数:',np.sum(np.where(a>30,1,0)))

[28 30 29 31 32 30 29]
平均气温是: 30.0
平均气温是:29.857
最高温度是: 32
最低温度是: 28
气温超过30的天数: 2
气温超过30的天数: 2


In [13]:
a = np.random.randint(0,10,(3,4))
print(a)
for i in range(0,4):
    print(f'第{i+1}列的最大值为:',np.max(a[:,i]))
    i +=1
for i in range(0,3):
    print(f'第{i+1}行的最大值为',np.max(a[i,:]))
    i +=1

[[6 9 8 5]
 [3 2 0 6]
 [4 5 0 0]]
第1列的最大值为: 6
第2列的最大值为: 9
第3列的最大值为: 8
第4列的最大值为: 6
第1行的最大值为 9
第2行的最大值为 6
第3行的最大值为 5


In [14]:
a = np.random.randint(0,10,(3,4))
print(a)
print('每一列的最大值为',np.max(a,axis=0))
print('每一行的最大值为',np.max(a,axis=1))
print(np.where(a%2==1,-1,a))

[[6 1 0 9]
 [7 7 3 7]
 [1 7 3 6]]
每一列的最大值为 [7 7 3 9]
每一行的最大值为 [9 7 7]
[[ 6 -1  0 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1  6]]
